### ISSUE TITLE
Broom build issue

### ISSUE THREAD

**Issue by graemeleehickey** [graemeleehickey/joineRML#64]
When building, I am getting the following error:

```r
   Error: processing vignette 'joineRML-broom.Rmd' failed with diagnostics:
   No tidy method for objects of class mjoint
   --- failed re-building ‘joineRML-broom.Rmd’
```

Can you investigate @ellessenne ?

**Comment by ellessenne** [comment]
Hi @graemeleehickey, unfortunately support for `joineRML` in `broom` has been removed once it was not on CRAN anymore (see [here](https://github.com/tidymodels/broom/commit/11c654ab6f5be6ea28849ab24cffc7dfe08c7988))... that's why the vignette is failing.
I opened an issue in the `broom` repository if you want to follow the discussion: tidymodels/broom#822

**Comment by graemeleehickey** [comment]
Thanks @ellessenne -- hopefully we can get this resolved before the next CRAN submission (which I was planning for once I resolve all the outstanding issues).

**Comment by ellessenne** [comment]
I'll try to see if I get some time to make a new PR in `broom`, should be easily fixable though!

**Comment by graemeleehickey** [comment]
Fixed
